# This requires a working build of lci, the windows build is currently inoperable



# PROGRAMS = ../add/Add ../max/Max ../max/MaxL ../max/Pong ../max/PongL ../max/Rect ../max/RectL
# ASSEMBLER = ./assembler.sh

# all: $(PROGRAMS)

# $(PROGRAMS):
# 	$(ASSEMBLER) $@.asm
